language: ruby
rvm:
  - "2.5.8"
  - "2.7.1"
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
before_script:
  - psql -c 'create database contribulator_test' -U postgres
cache: bundler
env:
  - DB=postgresql
addons:
  postgresql: "9.6"
