language: ruby
rvm:
  - "2.5.6"
  - "2.7.0-preview1"
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec && bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
before_script:
  - psql -c 'create database contribulator_test' -U postgres
cache: bundler
env:
  - DB=postgresql
addons:
  postgresql: "9.6"
